### ISSUE TITLE
Border radius missing on non-horizontal table cells

### ISSUE THREAD

**Issue by adam-earthscope** [Chalarangelo/mini.css#154]
* Framework Version: 3.0.1
* Flavor used: default
* Operating System/Browser:
* Code to reproduce:
* Screenshots:
* Bug description:
* Additional information (Optional):

[Note]: # (Please describe what the bug is, what component/module causes it and how it differs from expected/intended behavior)
[Note]: # (Include screenshots of the reported bug whenever possible to best clarify)
[Note]: # (Always try to include code to reproduce the problem, as well as system specifications to make tracking easier)
[Note]: # (Codepen links, additional information, suggestions, articles etc. are greatly appreciated)
[Note]: # (If you want to suggest a feature or your issue doesn't classify as a bug report, please do not use this template)

Horizontal tables have special handling to apply border-radius on the corner cells, but the regular table doesn't. A modified version of the horizontal table code fixes the issue for me:

```scss
table {
    thead tr:first-child th {
        &:first-child{
            border-top-left-radius: var(--universal-border-radius);
        }
        &:last-child{
            border-top-right-radius: var(--universal-border-radius);
        }
    }
    tbody tr:last-child td {
        &:first-child{
            border-bottom-left-radius: var(--universal-border-radius);
        }
        &:last-child{
            border-bottom-right-radius: var(--universal-border-radius);
        }
    }
}
```
