### ISSUE TITLE
Animated alert text is blurry in Chrome

### ISSUE THREAD

**Issue by Chalarangelo** [Chalarangelo/mini.css#35]
Using the following code produces a crisp result in Firefox, but a very blurry one in Chrome:

```
<div class="alert animated">
    <h3>Animated alert</h3>
</div>
```

The problem seems to be **webkit-related**, however there could be ways to find a workaround for it.

Any help provided in order to solve the issue is much appreciated.

**Comment by Chalarangelo** [comment]
**Update:** The above code does also work properly on IE 11 and the result is crispy and clean.

**Comment by Chalarangelo** [comment]
## Update

The issue is on Chrome's part ([link](https://bugs.chromium.org/p/chromium/issues/detail?id=521364)), however a temporary solution might be possible to implemented, by changing the animation to this:
```css
@-webkit-keyframes alert-anim {
  45% {
    -webkit-transform: scale(1);
    -webkit-transform-origin: 50% 50%;
  }
  50% {
    -webkit-transform: scale(1.005);
    -webkit-transform-origin: 50% 50%;
  }
  55% {
    -webkit-transform: scale(1);
    -webkit-transform-origin: 50% 50%;
  }
}
@keyframes alert-anim {
  45% {
    transform: scale(1);
    transform-origin: 50% 50%;
  }
  50% {
    transform: scale(1.005);
    transform-origin: 50% 50%;
  }
  55% {
    transform: scale(1);
    transform-origin: 50% 50%;
  }
}
```

The above fix is a two level solution, which does the following:
- Explicitly specifying the `transform-origin` seems to fix the issue under circumstances. 
- Removing the `0%` and `100%` steps keeps the animation exactly the same, while at the same time removing the blur from the element at times (tested locally), meaning that there is a brief blur period before and after the actual animation. 

Having tested this, it seems like an improvement over the previous iteration, so this will probably be included in the next update. For a permanent solution, we have to wait for the Chrome team to deal with the issue.
