### ISSUE TITLE
Hide for small screens

### ISSUE THREAD

**Issue by dioklecijan** [Chalarangelo/mini.css#61]
What class name should I use to hide column for the certain screen size?

```html
<div class="container">
  <div class="row">
    <div class="col-md-6">
      should be hidden for small screens
    </div>
    <div class="col-md-6 col-sm-12">
      should be always visible
    </div>
  </div>
</div>
```

**Comment by Chalarangelo** [comment]
In the current version of **mini.css** there is no class to deal with hiding content for certain screen sizes, due to certain accessibility concerns. This feature, however, was planned for an earlier release, but didn't make the cut. I have found myself dealing with this problem as well, so this feature *will be added in the next release*, which will be available late April. I know this is inconvenient, so I will provide you with a quick solution to the problem, so that you can deal with this for now and, when the next version is released, be sure to update to it, so that any problems that might come from these fixes can be dealt with.

## Temporary solution until next release

```css
/* Hide for smaller screens only - accessible */
@media (max-width: 767px) {
  .hidden-sm {
    position: absolute !important;
    width: 1px !important;
    height: 1px !important;
    margin: -1px !important;
    border: 0 !important;
    padding: 0 !important;
    clip: rect(0 0 0 0) !important;
    -webkit-clip-path: inset(100%) !important;
    clip-path: inset(100%) !important;
    overflow: hidden !important; 
  }
}
/* Hide for medium screens only - accessible */
@media (min-width: 768px) and (max-width: 1279px) {
  .hidden-md {
    position: absolute !important;
    width: 1px !important;
    height: 1px !important;
    margin: -1px !important;
    border: 0 !important;
    padding: 0 !important;
    clip: rect(0 0 0 0) !important;
    -webkit-clip-path: inset(100%) !important;
    clip-path: inset(100%) !important;
    overflow: hidden !important; 
  }
}
/* Hide for large screens only - accessible */
@media (min-width: 1280px) {
  .hidden-lg {
    position: absolute !important;
    width: 1px !important;
    height: 1px !important;
    margin: -1px !important;
    border: 0 !important;
    padding: 0 !important;
    clip: rect(0 0 0 0) !important;
    -webkit-clip-path: inset(100%) !important;
    clip-path: inset(100%) !important;
    overflow: hidden !important; 
  }
}
```

## Notes

- A **codepen** demonstration can be found [here](http://codepen.io/chalarangelo/pen/zZJRGL). 
- You would use `.hidden-sm` to do what you are trying to accomplish. Be warned that you need to deal with layout changes yourself in order to make the invisible element not cause any trouble (this is why the update will solve this in a better way, but the quick fix provided should be a good starting point). 
- If you do not want the hidden content to be accessible on smaller screens , you can replace the body of the classes with `display: none !important;` and it would accomplish the same.
- The coming update will almost certainly address this issue and provide a better solution that deals with layout changes. 
- The above code will probably *not* work in the next update, as `print` stylesheets are going to be added so almost all current media queries will be replaced with `screen`-specific media queries. If this issue is closed, the above fix will most likely be obsolete, seek out later comments for the current best practices.
