### ISSUE TITLE
Different font

### ISSUE THREAD

**Issue by MatiasConTilde** [Chalarangelo/mini.css#79]
How can I use a different font from the default?

**Comment by Chalarangelo** [comment]
There are at least two ways I can think of that will accomlish this:

### 1. Quick and dirty

Add this **after** loading **mini.css**:
```css
html, * {
  font-family: your-font-here;
}
/* 
  Use this to keep the default font styling for code elements 
  or replace the font-family as well 
*/
code, kbd, pre, samp {
  font-family: monospace, monospace;
}
```

This basically overrides the default fonts, so you don't have to mess with flavor files etc.

### 2. The right way

Edit the flavor file you are using (e.g. [default flavor file](https://github.com/Chalarangelo/mini.css/blob/master/src/flavors/mini-default.scss)). There is a line with the variable `$base-font-family` which you can replace to use the `font-family` of your choice. You can either `@import` the font file (e.g. as seen on the Sucroa [flavor file](https://github.com/Chalarangelo/mini.css/blob/master/src/flavors/mini-sucroa.scss)) or include it through your HTML page. Remember to compile the flavor file with a Sass preprocessor to turn it into a proper CSS file.
